// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foods/food.proto

package com.example.grpc.food;

public final class FoodOuterClass {
  private FoodOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FoodResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FoodResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string foods = 1;</code>
     * @return A list containing the foods.
     */
    java.util.List<java.lang.String>
        getFoodsList();
    /**
     * <code>repeated string foods = 1;</code>
     * @return The count of foods.
     */
    int getFoodsCount();
    /**
     * <code>repeated string foods = 1;</code>
     * @param index The index of the element to return.
     * @return The foods at the given index.
     */
    java.lang.String getFoods(int index);
    /**
     * <code>repeated string foods = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the foods at the given index.
     */
    com.google.protobuf.ByteString
        getFoodsBytes(int index);

    /**
     * <code>int32 responseCode = 2;</code>
     * @return The responseCode.
     */
    int getResponseCode();
  }
  /**
   * Protobuf type {@code FoodResponse}
   */
  public  static final class FoodResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FoodResponse)
      FoodResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FoodResponse.newBuilder() to construct.
    private FoodResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FoodResponse() {
      foods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FoodResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FoodResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                foods_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              foods_.add(s);
              break;
            }
            case 16: {

              responseCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          foods_ = foods_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.food.FoodOuterClass.internal_static_FoodResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.food.FoodOuterClass.internal_static_FoodResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.food.FoodOuterClass.FoodResponse.class, com.example.grpc.food.FoodOuterClass.FoodResponse.Builder.class);
    }

    public static final int FOODS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList foods_;
    /**
     * <code>repeated string foods = 1;</code>
     * @return A list containing the foods.
     */
    public com.google.protobuf.ProtocolStringList
        getFoodsList() {
      return foods_;
    }
    /**
     * <code>repeated string foods = 1;</code>
     * @return The count of foods.
     */
    public int getFoodsCount() {
      return foods_.size();
    }
    /**
     * <code>repeated string foods = 1;</code>
     * @param index The index of the element to return.
     * @return The foods at the given index.
     */
    public java.lang.String getFoods(int index) {
      return foods_.get(index);
    }
    /**
     * <code>repeated string foods = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the foods at the given index.
     */
    public com.google.protobuf.ByteString
        getFoodsBytes(int index) {
      return foods_.getByteString(index);
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 2;</code>
     * @return The responseCode.
     */
    public int getResponseCode() {
      return responseCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < foods_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, foods_.getRaw(i));
      }
      if (responseCode_ != 0) {
        output.writeInt32(2, responseCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < foods_.size(); i++) {
          dataSize += computeStringSizeNoTag(foods_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFoodsList().size();
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.grpc.food.FoodOuterClass.FoodResponse)) {
        return super.equals(obj);
      }
      com.example.grpc.food.FoodOuterClass.FoodResponse other = (com.example.grpc.food.FoodOuterClass.FoodResponse) obj;

      if (!getFoodsList()
          .equals(other.getFoodsList())) return false;
      if (getResponseCode()
          != other.getResponseCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFoodsCount() > 0) {
        hash = (37 * hash) + FOODS_FIELD_NUMBER;
        hash = (53 * hash) + getFoodsList().hashCode();
      }
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.grpc.food.FoodOuterClass.FoodResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.grpc.food.FoodOuterClass.FoodResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FoodResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FoodResponse)
        com.example.grpc.food.FoodOuterClass.FoodResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.grpc.food.FoodOuterClass.internal_static_FoodResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.grpc.food.FoodOuterClass.internal_static_FoodResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.grpc.food.FoodOuterClass.FoodResponse.class, com.example.grpc.food.FoodOuterClass.FoodResponse.Builder.class);
      }

      // Construct using com.example.grpc.food.FoodOuterClass.FoodResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        foods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.grpc.food.FoodOuterClass.internal_static_FoodResponse_descriptor;
      }

      @java.lang.Override
      public com.example.grpc.food.FoodOuterClass.FoodResponse getDefaultInstanceForType() {
        return com.example.grpc.food.FoodOuterClass.FoodResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.grpc.food.FoodOuterClass.FoodResponse build() {
        com.example.grpc.food.FoodOuterClass.FoodResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.grpc.food.FoodOuterClass.FoodResponse buildPartial() {
        com.example.grpc.food.FoodOuterClass.FoodResponse result = new com.example.grpc.food.FoodOuterClass.FoodResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          foods_ = foods_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.foods_ = foods_;
        result.responseCode_ = responseCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.grpc.food.FoodOuterClass.FoodResponse) {
          return mergeFrom((com.example.grpc.food.FoodOuterClass.FoodResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.grpc.food.FoodOuterClass.FoodResponse other) {
        if (other == com.example.grpc.food.FoodOuterClass.FoodResponse.getDefaultInstance()) return this;
        if (!other.foods_.isEmpty()) {
          if (foods_.isEmpty()) {
            foods_ = other.foods_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFoodsIsMutable();
            foods_.addAll(other.foods_);
          }
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.grpc.food.FoodOuterClass.FoodResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.grpc.food.FoodOuterClass.FoodResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList foods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFoodsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          foods_ = new com.google.protobuf.LazyStringArrayList(foods_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @return A list containing the foods.
       */
      public com.google.protobuf.ProtocolStringList
          getFoodsList() {
        return foods_.getUnmodifiableView();
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @return The count of foods.
       */
      public int getFoodsCount() {
        return foods_.size();
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @param index The index of the element to return.
       * @return The foods at the given index.
       */
      public java.lang.String getFoods(int index) {
        return foods_.get(index);
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the foods at the given index.
       */
      public com.google.protobuf.ByteString
          getFoodsBytes(int index) {
        return foods_.getByteString(index);
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @param index The index to set the value at.
       * @param value The foods to set.
       * @return This builder for chaining.
       */
      public Builder setFoods(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFoodsIsMutable();
        foods_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @param value The foods to add.
       * @return This builder for chaining.
       */
      public Builder addFoods(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFoodsIsMutable();
        foods_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @param values The foods to add.
       * @return This builder for chaining.
       */
      public Builder addAllFoods(
          java.lang.Iterable<java.lang.String> values) {
        ensureFoodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, foods_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFoods() {
        foods_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string foods = 1;</code>
       * @param value The bytes of the foods to add.
       * @return This builder for chaining.
       */
      public Builder addFoodsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFoodsIsMutable();
        foods_.add(value);
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 2;</code>
       * @return The responseCode.
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FoodResponse)
    }

    // @@protoc_insertion_point(class_scope:FoodResponse)
    private static final com.example.grpc.food.FoodOuterClass.FoodResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.grpc.food.FoodOuterClass.FoodResponse();
    }

    public static com.example.grpc.food.FoodOuterClass.FoodResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FoodResponse>
        PARSER = new com.google.protobuf.AbstractParser<FoodResponse>() {
      @java.lang.Override
      public FoodResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FoodResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FoodResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FoodResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.grpc.food.FoodOuterClass.FoodResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FoodResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FoodResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020foods/food.proto\032\022common/vo/vo.proto\"3" +
      "\n\014FoodResponse\022\r\n\005foods\030\001 \003(\t\022\024\n\014respons" +
      "eCode\030\002 \001(\0052%\n\004Food\022\035\n\004list\022\006.Empty\032\r.Fo" +
      "odResponseB\027\n\025com.example.grpc.foodb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.grpc.common.vo.Vo.getDescriptor(),
        });
    internal_static_FoodResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FoodResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FoodResponse_descriptor,
        new java.lang.String[] { "Foods", "ResponseCode", });
    com.example.grpc.common.vo.Vo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
